### ISSUE TITLE
Unusual file structure

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/error-handling-workshop#19]
Based on feedback recorded in #17 

File structure is not typical of projects students have seen. Indeed, it is a remnant of the original version of the workshop that I didn't think was important enough to change. But in order to avoid needless confusion, I'll change the file structure to be more conventional.

**Comment by jsms90** [comment]
+ `modules` rather than `src`
  + `index.js` rather than `server.js` & `router.js` - like in [node intro workshop](https://github.com/foundersandcoders/Node-Intro-Workshop/tree/mentor-walkthrough/step-5) and [node girls workshop](https://github.com/node-girls/workshop-cms/blob/master/step02.md) from week before
  + what `acceptance` is for
  + `solution` within `acceptance`
