### ISSUE TITLE
Ordering of approaches

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/error-handling-workshop#33]
Is it worth rearranging the order of the approaches in this workshop? Most students only got to `Approach 2`, which meant that they missed all the fab information on error first callbacks, which is the most important concept for them to be able to write Node code

**Comment by veredrec** [comment]
@astroash agree! The same comment was raised in Nazareth. 

Our suggestion for the order is: 
1. `Error-First Callbacks`
2. `Throwing and Catching Errors`
3. `Returning Errors to the Caller`

**Comment by polyccon** [comment]
The problem could also be solved by allowing more time for the workshop, and perhaps adding slides for the 3 approaches in the introductory presentation to the workshop. I wouldn't change the order just because it's easier to think in terms of synchronous code when being first acquainted with a new concept such error handling. Perhaps there could be a complementary workshop such as the one we (FAC11) had on week 7?

**Comment by astroash** [comment]
@polyccon  which complementary workshop are you referring to?
